### ISSUE TITLE
Create a board given title

### ISSUE THREAD

**Issue by shahankit** [plish/Trolly#19]
@plish It may seem obvious but I'm unable to find as to how do I create a board given it's name? Can you please help as to how I do that?

**Comment by shahankit** [comment]
To narrow it down how do I call this api : https://trello.com/docs/api/board/index.html#post-1-boards

**Comment by plish** [comment]
@shahankit This isn't currently available through the API. I am trying to find the time to update the lib but if you would like to add this feature please feel free to submit a pull request.

Otherwise I will update this issue when I have updated the API.

Thanks,
P

**Comment by shahankit** [comment]
generated pull request #20
