### ISSUE TITLE
No Install instructions, bad imports

### ISSUE THREAD

**Issue by its-rigs** [plish/Trolly#2]
"I tried running Trolly directly but I wasn't sure how to set it up, there are no install instructions etc. I tried running Trolly's tests but I get:

$ python ./tests.py

Traceback (most recent call last):

File "./tests.py", line 10, in <module>

from src.lib.trello.trello.client import Client

ImportError: No module named src.lib.trello.trello.client

I'm no python expert either, I'm not too sure on how the paths etc need to be set up for this import to work -- can you help?"

**Comment by shahankit** [comment]
hey @plish can you help if you understood how to use it? I cloned the repository and first tried the command `python authorise.py -a <APP_KEY FROM TRELLO> tempApp`. It returns me ImportError: No module named trolly.client.
