### ISSUE TITLE
tests require network connection

### ISSUE THREAD

**Issue by mcepl** [plish/Trolly#46]
When trying to run the test suite while building openSUSE packages for Trolly, we don’t have any network connection available outside of the build system. Therefore all tests fail. Is it possible to mock those network connections somehow?

[Complete build log with all details](https://github.com/its-rigs/Trolly/files/5098119/_log.txt)

**Comment by its-rigs** [comment]
Hi, I haven't supported this codebase for some time. I had a look at the tests and honestly they're basically all worthless. They're integration tests as opposed to unit tests, so they require a network connection. 

I did want to do a big rewrite but it seems like py-trello has more ongoing support, so it didn't seem worth it.

If you can think of a quick way to solve the issue or would like to put in a PR I'm happy to merge and publish changes.

**Comment by mcepl** [comment]
Thank you, I will just give up on the test suite as the bad job until I hear something else from you.
